apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_SERVICE_ACCOUNT}
  namespace: ${APP_NAMESPACE}
  annotations:
    azure.workload.identity/client-id: ${WORKLOAD_IDENTITY_CLIENT_ID}
    azure.workload.identity/tenant-id: ${TENANT_ID}
